### ISSUE TITLE
Glossary entries multiplication issue

### ISSUE THREAD

**Issue by GCappiello1** [dthies/moodle-format_popups#10]
Hi,

I believe I have discovered a problem with how this plugin reacts with Moodle's glossary function. 

It appears to interact badly with glossary entries that are linked to text on a page where the format has been set up to "pop-up activities". Where a glossary link is clicked before a pop-up activity is selected it acts normally. If a pop-up activity (specifically a video added as a page or an H5P package) is accessed, and then the glossary link is selected, the glossary entry appears multiple times (screenshot attached). 
![pop-up activities glossary issue](https://user-images.githubusercontent.com/97512799/154491754-6846d25d-8f4a-4c94-a5c1-9807ab877888.png)

Thanks

**Comment by dthies** [comment]
Hi,
I think this was a Moodle core bug, and that it may have been fixed in the latest version. I was able to reproduce it before, but not after the latest 3.11 upgrade. Can you verify that?

**Comment by dthies** [comment]
I fixed this in the latest release. The new listener was added when a modal was opened with filtered text. This meant that an extra autolink modal appeared when a term was clicked for each extra listener. Loading the listener is only down now on the main page, not the modals. This may mean under some circumstances the autolinking may not work, but will see.
