### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by dinism** [dthies/moodle-format_popups#14]
In Moodle 3.11.11
![image](https://user-images.githubusercontent.com/14828021/210411163-82d076db-1e08-41ac-9f82-7285e7805a6f.png)
When i tried to update to 
![image](https://user-images.githubusercontent.com/14828021/210409908-04c79c0d-a02c-43ef-92be-1664aafc9cb0.png)
I got THIS:
Downloading format_popups ... OK
Validating format_popups ... Error
  **[Error] Required Moodle version [2022030300]** 
Installation aborted due to validation failure

Any suggestion?

I have installed (working OK)
![image](https://user-images.githubusercontent.com/14828021/210411626-cba7cc17-a5d1-43ad-80e2-fa4c9109fb41.png)

**Comment by dthies** [comment]
Hi,
I think what you have may be correct. I think that version may be marked wrong in the data base. There was a change in the core course format api in 4.0. So there should be separate versions above and below 4.0.

**Comment by dthies** [comment]
That looks to be the case. I updated the database entry. All the recent changes have to do with course index that was added feature in 4.0. The older version should be most recent for 3.11
