### ISSUE TITLE
Dependency on block_deft

### ISSUE THREAD

**Issue by sharpchi** [dthies/moodle-format_popups#15]
If you try to add functions to a web service you get "Exception - Class "block_deft\external\renew_token" not found". If you don't have block_deft installed. block_deft should at least be a dependency in the version file.

https://github.com/dthies/moodle-format_popups/blob/53abf4f941787f6859c8af1a21a9a2a3894e4964/classes/external/renew_token.php#L34

**Comment by dthies** [comment]
This should be fixed in the latest release. Sorry, I did not see this earlier.
