### ISSUE TITLE
Bugs echos - admin and user Coding erorrs

### ISSUE THREAD

**Issue by lukascelinak** [dthies/moodle-format_popups#5]
Tested on Moodle 3.11.2+ (Build: 20210805) and  Moodle 3.11.1 (Build: 20210712)

Worklfow standard user:
Module URL-> click -> open in new window -> go back to course window -> codingerror

Coding error detected, it must be fixed by a programmer: Cannot call moodle_page::add_body_class after output has been started.
File: /lib/pagelib.php
Line: 1210
Stack trace:

Error code: codingerror
* line 1210 of /lib/pagelib.php: coding_exception thrown
* line 1300 of /lib/outputrenderers.php: call to moodle_page->add_body_class()
* line 171 of /mod/url/locallib.php: call to core_renderer->header()
* line 271 of /mod/url/locallib.php: call to url_print_header()
* line 100 of /course/format/popups/classes/local/mod_url.php: call to url_print_workaround()
* line 91 of /course/format/popups/lib.php: call to format_popups\local\mod_url->render()
* line 7917 of /lib/moodlelib.php: call to format_popups_output_fragment_mod()
* line 423 of /lib/external/externallib.php: call to component_callback()
* line 261 of /lib/externallib.php: call to core_external::get_fragment()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

Loged as admin with same workflow:
codingerror
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 2 and state 1 was requested.
File: /lib/pagelib.php
Line: 980
Stack trace:

Error code: codingerror
* line 980 of /lib/pagelib.php: coding_exception thrown
* line 1321 of /lib/outputrenderers.php: call to moodle_page->set_state()
* line 171 of /mod/url/locallib.php: call to core_renderer->header()
* line 271 of /mod/url/locallib.php: call to url_print_header()
* line 100 of /course/format/popups/classes/local/mod_url.php: call to url_print_workaround()
* line 91 of /course/format/popups/lib.php: call to format_popups\local\mod_url->render()
* line 7917 of /lib/moodlelib.php: call to format_popups_output_fragment_mod()
* line 423 of /lib/external/externallib.php: call to component_callback()
* line 261 of /lib/externallib.php: call to core_external::get_fragment()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by dthies** [comment]
Thank you for reporting this. I was able to reproduce with your instructions. The open link a window setting is attempting to do something different that the plugin is. It is opening an completely new browser window in addition to the modal. This plugin in should work if you change the setting to auto or open. However, I should do something to try an prevent it from trying to open both a new window and a modal.

**Comment by dthies** [comment]
I updated with a fix now so that it will not open a modal if the url is set to Open popup. If you want the modal, you should change the setting to Auto or Open.
